# Project information
site_name: operator-sample-go-documentation
site_url: https://github.com/thomassuedbroecker/operator-sample-go-documentation
site_author:  Adam de Leeuw, Alain Airom, Diwakar Tiwari, Niklas Heidloff,  Sundeep Binaylal Golla, Thomas Suedbroecker

# Repository
repo_name: operator-sample-go-documentation
repo_url: https://github.com/IBM/operator-sample-go
edit_uri: edit/main/documentation
docs_dir: documentation

# Navigation
nav:
  - 1. Introduction:
    - 1.1 Overview: ./template.md
    - 1.2 Niklas overview video: ./template.md
    - 1.3 Adam demo video: ./template.md
    - 1.4 Masterclass video: ./template.md
  - 2. Dev env:
    - 2.1 Overview: ./template.md
    - 2.2 Prereqs: ./template.md
    - 2.3 Setup of IKS: ./template.md
    - 2.4 Setup of ROKS: ./template.md
    - 2.5 Run operators locally: ./template.md
    - 2.6 Run operators without OLM: ./template.md
    - 2.7 Run operators with OLM: ./template.md
  - 3. Demos:
    - 3.1 Overview: ./template.md
    - 3.2 OperatorHub: ./template.md
    - 3.3 Database backup: ./template.md
    - 3.4 Auto-scaler: ./template.md
  - 4. Automated build and deployment:
    - 4.1 Overview: ./template.md
    - 4.2 Kubernetes: ./template.md
    - 4.4 OpenShift: ./template.md
  - 5. Overview and Scenarios:
    - 5.1 Overview: ./template.md
    - 5.2 Why you should build Kubernetes Operators: ./template.md
    - 5.3 Day 2 Scenario - Automatically Archiving Data: ./template.md
    - 5.4 Day 2 Scenario - Automatically Scaling Applications: ./template.md
    - 5.6 The Kubernetes Operator Metamodel: ./template.md
  - 6. Basic Capabilities :
    - 6.1 Overview: ./template.md
    - 6.2 Creating and updating Resources: ./template.md
    - 6.3 Deleting Resources: ./template.md
    - 6.4 Storing State of Resources with Conditions: ./template.md
    - 6.5 Finding out the Kubernetes Versions and Capabilities: ./template.md
    - 6.6 Configuring Webhooks: ./template.md
    - 6.7 Initialization and Validation Webhooks: ./template.md
    - 6.8 Converting Custom Resource Versions: ./template.md
    - 6.9 Defining Dependencies: ./template.md
  - 7. Advanced Capabilities:
    - 7.1 Overview: ./template.md
    - 7.2 Exporting Metrics from Kubernetes Apps for Prometheus: ./template.md
    - 7.3 Accessing Kubernetes from Go Applications: ./template.md
    - 7.4 How to build your own Database on Kubernetes: ./template.md
    - 7.5 Building Databases on Kubernetes with Quarkus: ./template.md
  - 8. Golang:
    - 8.1 Overview: ./template.md
    - 8.2 Importing Go Modules in Operators: ./template.md
    - 8.3 Accessing third Party Custom Resources in Go Operators: ./template.md
    - 8.4 Using object-oriented Concepts in Golang based Operators: ./template.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
#copyright: Copyright &copy; 2022 IBM Developer

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    # .svg automatically appended
    # logo: ibm_8bar_reverse_2
    logo: material/library
  features:
    # - navigation.tabs
    - navigation.instant
    # - navigation.expand
  palette:
    scheme: default
    primary: black
    accent: blue
  # palette:
  #  scheme: default
  #  primary: blue
  #  accent: blue
  # enable if you want to use a custom icon
  # custom_dir: overrides

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/IBM/operator-sample-go
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ibmdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ibm/
  generator: false

extra_css:
  - docs/stylesheets/extra.css
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
